Repository axelarnetwork/axelar-core, pull requests merged in 2021-12, with the labels that each got.

#1011 feat(snapshot): init/export genesis
  cmd/axelard/cmd/gensnapshot.go
  docs/cli/axelard_set-genesis-snapshot.md
  docs/proto/proto-docs.md
  proto/snapshot/v1beta1/genesis.proto
  proto/snapshot/v1beta1/params.proto
  proto/snapshot/v1beta1/types.proto
  x/bitcoin/types/mock/expected_keepers.go
  x/evm/keeper/msg_server.go
  x/evm/keeper/msg_server_test.go
  x/evm/types/mock/expected_keepers.go
  x/snapshot/exported/mock/types.go
  x/snapshot/exported/types.go
  x/snapshot/genesis.go
  x/snapshot/keeper/genesis.go
  x/snapshot/keeper/genesis_test.go
  x/snapshot/keeper/keeper.go
  x/snapshot/keeper/keeper_test.go
  x/snapshot/keeper/msg_server.go
  x/snapshot/module.go
  x/snapshot/types/genesis.go
  x/snapshot/types/genesis.pb.go
  x/snapshot/types/params.go
  x/snapshot/types/params.pb.go
  x/snapshot/types/types.go
  x/snapshot/types/types.pb.go
  x/tss/types/mock/expected_keepers.go
Labels: enhancement

#995 feat(tss): multisig governance key
  app/app.go
  buf.yaml
  cmd/axelard/cmd/gengovkey.go
  cmd/axelard/cmd/root.go
  docs/cli/axelard.md
  docs/cli/axelard_query_tss.md
  docs/cli/axelard_query_tss_governance-key.md
  docs/cli/axelard_set-governance-key.md
  docs/cli/axelard_tx_tss.md
  docs/cli/axelard_tx_tss_update-governance-key.md
  docs/cli/toc.md
  docs/proto/proto-docs.md
  proto/tss/v1beta1/genesis.proto
  proto/tss/v1beta1/query.proto
  proto/tss/v1beta1/service.proto
  proto/tss/v1beta1/tx.proto
  x/ante/restricted_tx.go
  x/ante/types/expected_keepers.go
  x/tss/client/cli/query.go
  x/tss/client/cli/tx.go
  x/tss/client/rest/tx.go
  x/tss/genesis.go
  x/tss/handler.go
  x/tss/keeper/grpc_query.go
  x/tss/keeper/keeper.go
  x/tss/keeper/msg_server.go
  x/tss/keeper/querier.go
  x/tss/module.go
  x/tss/types/codec.go
  x/tss/types/expected_keepers.go
  x/tss/types/genesis.go
  x/tss/types/genesis.pb.go
  x/tss/types/mock/expected_keepers.go
  x/tss/types/msg_update_governance_key.go
  x/tss/types/query.pb.go
  x/tss/types/service.pb.go
  x/tss/types/service.pb.gw.go
  x/tss/types/tx.pb.go
Labels: enhancement

#1032 feat: export axelarnet genesis state
  docs/proto/proto-docs.md
  proto/axelarnet/v1beta1/genesis.proto
  proto/axelarnet/v1beta1/types.proto
  x/axelarnet/genesis.go
  x/axelarnet/keeper/genesis.go
  x/axelarnet/keeper/genesis_test.go
  x/axelarnet/keeper/keeper.go
  x/axelarnet/keeper/msg_server.go
  x/axelarnet/keeper/msg_server_test.go
  x/axelarnet/module.go
  x/axelarnet/types/expected_keepers.go
  x/axelarnet/types/genesis.go
  x/axelarnet/types/genesis.pb.go
  x/axelarnet/types/mock/expected_keepers.go
  x/axelarnet/types/types.go
  x/axelarnet/types/types.pb.go
Labels: enhancement

#1040 feat(nexus): linked addresses validation
  app/app.go
  cmd/axelard/cmd/genchain.go
  docs/cli/axelard_tx_axelarnet_add-cosmos-based-chain.md
  docs/cli/toc.md
  docs/proto/proto-docs.md
  proto/axelarnet/v1beta1/tx.proto
  proto/axelarnet/v1beta1/types.proto
  proto/nexus/exported/v1beta1/types.proto
  x/axelarnet/client/cli/tx.go
  x/axelarnet/client/rest/tx.go
  x/axelarnet/exported/params.go
  x/axelarnet/keeper/address_validator.go
  x/axelarnet/keeper/genesis.go
  x/axelarnet/keeper/genesis_test.go
  x/axelarnet/keeper/keeper.go
  x/axelarnet/keeper/keeper_test.go
  x/axelarnet/keeper/msg_server.go
  x/axelarnet/keeper/msg_server_test.go
  x/axelarnet/types/expected_keepers.go
  x/axelarnet/types/mock/expected_keepers.go
  x/axelarnet/types/msg_add_chain.go
  x/axelarnet/types/tx.pb.go
  x/axelarnet/types/types.go
  x/axelarnet/types/types.pb.go
  x/bitcoin/exported/params.go
  x/bitcoin/keeper/address_validator.go
  x/bitcoin/keeper/msg_server.go
  x/bitcoin/keeper/msg_server_test.go
  x/bitcoin/types/expected_keepers.go
  x/bitcoin/types/mock/expected_keepers.go
  x/evm/exported/params.go
  x/evm/keeper/address_validator.go
  x/evm/keeper/msg_server.go
  x/evm/keeper/msg_server_test.go
  x/evm/keeper/querier_test.go
  x/evm/types/expected_keepers.go
  x/evm/types/mock/expected_keepers.go
  x/evm/types/msg_add_chain.go
  x/nexus/exported/types.go
  x/nexus/exported/types.pb.go
  x/nexus/keeper/keeper.go
  x/nexus/keeper/keeper_test.go
  x/nexus/types/expected_keepers.go
  x/nexus/types/mock/expected_keepers.go
  x/nexus/types/router.go
  x/tss/keeper/msg_server_test.go
Labels: enhancement

#1036 feat(tss): init/export genesis
  cmd/axelard/cmd/gengovkey.go
  docs/proto/proto-docs.md
  proto/tss/exported/v1beta1/types.proto
  proto/tss/v1beta1/genesis.proto
  proto/tss/v1beta1/params.proto
  proto/tss/v1beta1/types.proto
  x/evm/types/expected_keepers.go
  x/evm/types/mock/expected_keepers.go
  x/tss/abci.go
  x/tss/exported/types.go
  x/tss/exported/types.pb.go
  x/tss/genesis.go
  x/tss/keeper/genesis.go
  x/tss/keeper/keeper.go
  x/tss/keeper/keeperKeygen.go
  x/tss/keeper/keeperKeygen_test.go
  x/tss/keeper/keeperSign.go
  x/tss/keeper/keeper_test.go
  x/tss/keeper/msg_server.go
  x/tss/keeper/recovery.go
  x/tss/module.go
  x/tss/types/expected_keepers.go
  x/tss/types/genesis.go
  x/tss/types/genesis.pb.go
  x/tss/types/mock/expected_keepers.go
  x/tss/types/params.pb.go
  x/tss/types/types.go
  x/tss/types/types.pb.go
Labels: enhancement

#1037 feat: minimum deposit amount
  docs/cli/axelard_tx_evm_create-deploy-token.md
  docs/cli/toc.md
  docs/proto/proto-docs.md
  proto/axelarnet/v1beta1/params.proto
  proto/evm/v1beta1/tx.proto
  proto/evm/v1beta1/types.proto
  x/axelarnet/keeper/keeper.go
  x/axelarnet/keeper/msg_server.go
  x/axelarnet/keeper/msg_server_test.go
  x/axelarnet/types/expected_keepers.go
  x/axelarnet/types/mock/expected_keepers.go
  x/axelarnet/types/params.go
  x/axelarnet/types/params.pb.go
  x/bitcoin/keeper/keeper.go
  x/bitcoin/keeper/msg_server.go
  x/bitcoin/keeper/msg_server_test.go
  x/bitcoin/types/expected_keepers.go
  x/bitcoin/types/mock/expected_keepers.go
  x/evm/client/cli/tx.go
  x/evm/client/rest/tx.go
  x/evm/keeper/chainKeeper.go
  x/evm/keeper/msg_server.go
  x/evm/keeper/msg_server_test.go
  x/evm/types/expected_keepers.go
  x/evm/types/mock/expected_keepers.go
  x/evm/types/msg_create_deploy_token.go
  x/evm/types/tests/types_test.go
  x/evm/types/tx.pb.go
  x/evm/types/types.go
  x/evm/types/types.pb.go
  x/nexus/exported/types.go
  x/nexus/keeper/keeper.go
  x/nexus/keeper/keeper_test.go
Labels: enhancement

#1044 feat(tss): init/export genesis(signature)
  docs/proto/proto-docs.md
  proto/tss/v1beta1/genesis.proto
  proto/tss/v1beta1/types.proto
  x/bitcoin/types/expected_keepers.go
  x/bitcoin/types/mock/expected_keepers.go
  x/evm/types/expected_keepers.go
  x/evm/types/mock/expected_keepers.go
  x/snapshot/exported/mock/types.go
  x/snapshot/exported/types.go
  x/snapshot/keeper/keeper.go
  x/snapshot/keeper/keeper_test.go
  x/tests/chainSetup.go
  x/tss/exported/types.go
  x/tss/keeper/genesis.go
  x/tss/keeper/keeper.go
  x/tss/keeper/keeperSign.go
  x/tss/keeper/validator.go
  x/tss/types/expected_keepers.go
  x/tss/types/genesis.go
  x/tss/types/genesis.pb.go
  x/tss/types/mock/expected_keepers.go
  x/tss/types/types.go
  x/tss/types/types.pb.go
Labels: enhancement

#1042 feat(nexus): init/export genesis
  cmd/axelard/cmd/genchain.go
  docs/proto/proto-docs.md
  proto/nexus/exported/v1beta1/types.proto
  proto/nexus/v1beta1/genesis.proto
  proto/nexus/v1beta1/params.proto
  proto/nexus/v1beta1/types.proto
  x/axelarnet/keeper/genesis_test.go
  x/axelarnet/keeper/keeper.go
  x/axelarnet/keeper/msg_server.go
  x/axelarnet/keeper/msg_server_test.go
  x/axelarnet/types/expected_keepers.go
  x/axelarnet/types/mock/expected_keepers.go
  x/bitcoin/keeper/msg_server.go
  x/bitcoin/keeper/msg_server_test.go
  x/bitcoin/types/expected_keepers.go
  x/bitcoin/types/mock/expected_keepers.go
  x/evm/keeper/msg_server.go
  x/evm/keeper/msg_server_test.go
  x/evm/types/expected_keepers.go
  x/evm/types/mock/expected_keepers.go
  x/nexus/exported/types.go
  x/nexus/exported/types.pb.go
  x/nexus/genesis.go
  x/nexus/keeper/address.go
  x/nexus/keeper/chain.go
  x/nexus/keeper/genesis.go
  x/nexus/keeper/genesis_test.go
  x/nexus/keeper/grpc_query.go
  x/nexus/keeper/keeper.go
  x/nexus/keeper/nonce.go
  x/nexus/keeper/transfer.go
  x/nexus/module.go
  x/nexus/types/expected_keepers.go
  x/nexus/types/genesis.go
  x/nexus/types/genesis.pb.go
  x/nexus/types/mock/expected_keepers.go
  x/nexus/types/params.go
  x/nexus/types/params.pb.go
  x/nexus/types/types.go
  x/nexus/types/types.pb.go
Labels: enhancement

#1045 feat: export evm genesis state
  app/app.go
  app/params/encoding.go
  app/params/proto.go
  cmd/axelard/cmd/gencontracts.go
  cmd/axelard/cmd/gennetwork.go
  cmd/axelard/cmd/root.go
  docs/cli/axelard_query_evm.md
  docs/cli/axelard_query_evm_signed-tx.md
  docs/cli/toc.md
  docs/proto/proto-docs.md
  proto/evm/v1beta1/genesis.proto
  proto/evm/v1beta1/params.proto
  proto/evm/v1beta1/types.proto
  proto/nexus/v1beta1/types.proto
  utils/queuer.go
  x/axelarnet/keeper/genesis_test.go
  x/axelarnet/keeper/keeper_test.go
  x/bitcoin/keeper/keeper_test.go
  x/bitcoin/types/tests/types_test.go
  x/evm/client/cli/query.go
  x/evm/client/rest/query.go
  x/evm/client/rest/tx.go
  x/evm/genesis.go
  x/evm/keeper/baseKeeper.go
  x/evm/keeper/chainKeeper.go
  x/evm/keeper/genesis.go
  x/evm/keeper/genesis_test.go
  x/evm/keeper/keeper_test.go
  x/evm/keeper/msg_server.go
  x/evm/keeper/msg_server_test.go
  x/evm/keeper/querier.go
  x/evm/keeper/querier_test.go
  x/evm/module.go
  x/evm/types/expected_keepers.go
  x/evm/types/genesis.go
  x/evm/types/genesis.pb.go
  x/evm/types/mock/expected_keepers.go
  x/evm/types/params.go
  x/evm/types/params.pb.go
  x/evm/types/tests/types_test.go
  x/evm/types/testutils/types.go
  x/evm/types/types.go
  x/evm/types/types.pb.go
  x/nexus/keeper/genesis_test.go
  x/nexus/keeper/keeper_test.go
  x/nexus/types/types.pb.go
  x/reward/keeper/reward_pool_test.go
  x/snapshot/keeper/genesis_test.go
  x/snapshot/keeper/keeper_test.go
  x/tests/chainSetup.go
  x/tss/keeper/keeper_test.go
  x/tss/types/types_test.go
  x/vote/keeper/genesis_test.go
  x/vote/types/types_test.go
Labels: enhancement

#1056 fix: the default evm genesis state is now valid
  x/evm/keeper/genesis_test.go
  x/evm/module.go
  x/evm/types/genesis.go
  x/evm/types/types.go
Labels: bug

#1084 fix: make Link events consistent on axelarnet and evm
  go.sum
  x/evm/keeper/msg_server.go
Labels: bug

#1093 fix: return an expected error when the broadcast result code != 0
  cmd/axelard/cmd/vald/broadcaster/broadcast.go
Labels: bug

#1094 fix: return a registered error when the broadcast result code != 0
  cmd/axelard/cmd/vald/broadcaster/broadcast.go
Labels: bug

#1096 test(genesis): default genesis states should be valid and make nexus genesis test deterministic
  x/axelarnet/types/genesis_test.go
  x/axelarnet/types/types.go
  x/bitcoin/types/genesis_test.go
  x/evm/types/genesis_test.go
  x/nexus/keeper/genesis_test.go
  x/nexus/types/genesis_test.go
  x/permission/types/genesis_test.go
  x/reward/types/genesis_test.go
  x/snapshot/types/genesis_test.go
  x/tss/module.go
  x/tss/types/genesis.go
  x/tss/types/genesis_test.go
  x/vote/types/genesis_test.go
Labels: test

#1102 feat(reward): split external chain rewards by consensus power
  x/reward/abci.go
Labels: enhancement

#1105 fix(snapshot): remove chain maintainer on proxy deactivation
  app/app.go
  x/reward/abci.go
  x/reward/types/expected_keepers.go
  x/reward/types/mock/expected_keepers.go
  x/snapshot/handler.go
  x/snapshot/keeper/keeper.go
  x/snapshot/keeper/msg_server.go
  x/snapshot/module.go
  x/snapshot/types/expected_keepers.go
  x/tss/keeper/querier.go
Labels: bug

#1095 fix(tss): move multisig completion logic in the EndBlocker to avoid gas issue of the very last signature submitter
  go.mod
  go.sum
  x/snapshot/exported/mock/types.go
  x/tss/abci.go
  x/tss/keeper/keeperSign.go
  x/tss/keeper/msg_server.go
Labels: bug

#1115 fix(evm): set latest batched commands ID on import
  x/evm/keeper/genesis.go
  x/evm/types/genesis.go
Labels: bug

#1118 fix(axelarnet): genesis file validation
  x/axelarnet/module.go
Labels: bug

#1088 fix(evm): command batch re-signing
  x/evm/keeper/chainKeeper.go
  x/evm/keeper/genesis.go
  x/evm/keeper/msg_server.go
  x/evm/keeper/tss_router.go
  x/evm/types/expected_keepers.go
  x/evm/types/mock/expected_keepers.go
  x/tss/abci.go
  x/tss/keeper/msg_server.go
Labels: bug

#1123 fix(axelarnet): collector address validation
  x/axelarnet/types/genesis.go
Labels: bug

#1109 feat(evm): additional command queries
  docs/cli/axelard_query_evm.md
  docs/cli/axelard_query_evm_command.md
  docs/cli/axelard_query_evm_pending-commands.md
  docs/cli/toc.md
  docs/proto/proto-docs.md
  proto/evm/v1beta1/query.proto
  utils/mock/queuer.go
  utils/queuer.go
  x/evm/client/cli/query.go
  x/evm/client/query.go
  x/evm/client/rest/query.go
  x/evm/client/rest/tx.go
  x/evm/keeper/chainKeeper.go
  x/evm/keeper/keeper_test.go
  x/evm/keeper/querier.go
  x/evm/keeper/querier_test.go
  x/evm/types/expected_keepers.go
  x/evm/types/mock/expected_keepers.go
  x/evm/types/query.pb.go
  x/evm/types/tests/types_test.go
  x/evm/types/types.go
Labels: enhancement

#1022 feat(ci): sign released containers with sigstore
  .github/workflows/build-docker-image-and-binaries.yaml
Labels: enhancement

#1119 chore: request for additional attributes on emitted poll events for link, deposit txs
  x/evm/keeper/msg_server.go
  x/evm/types/events.go
Labels: enhancement

#1132 fix(evm): token capacity can be zero
  x/evm/types/types.go
Labels: bug

#1166 fix(vald): allow keyring type to be set via environment variable
  cmd/axelard/cmd/vald/start.go
Labels: bug

#1169 feat(app): enable feegrant
  app/app.go
Labels: enhancement
