Repository axelarnetwork/axelar-core, pull requests merged in 2022-10, with the labels that each got.

#1768 fix(nexus)!: recipient chain foreign asset check
  go.mod
  go.sum
  x/nexus/keeper/keeper_test.go
  x/nexus/keeper/transfer.go
  x/nexus/keeper/transfer_test.go
Labels: bug

#1765 refactor(evm): remove evm gateway status which is deprecated
  docs/proto/proto-docs.md
  proto/axelar/evm/v1beta1/types.proto
  x/evm/types/expected_keepers.go
  x/evm/types/genesis.go
  x/evm/types/testutils/types.go
  x/evm/types/types.pb.go
Labels: refactor

#1747 refactor(axelarnet)!: add coin struct to handle transfer logic
  x/axelarnet/keeper/coin.go
  x/axelarnet/keeper/coin_test.go
  x/axelarnet/keeper/ibc_transfer.go
  x/axelarnet/keeper/msg_server.go
  x/axelarnet/keeper/msg_server_test.go
  x/axelarnet/types/testutils/types.go
  x/axelarnet/types/types.go
Labels: refactor

#1778 fix(nexus): add missing amount field to nexus fee event
  x/nexus/keeper/transfer.go
Labels: backport needed

#1794 fix: clean up go mod
  go.mod
  go.sum
  sdk-utils/broadcast/broadcast_test.go
  utils/proto.go
  utils/proto_test.go
  x/multisig/keeper/msg_server_test.go
  x/permission/keeper/genesis_test.go
  x/reward/keeper/msg_server_test.go
  x/vote/keeper/keeper.go
  x/vote/keeper/poll.go
Labels: bug, backport needed

#1706 feat(axelarnet): genesis state import and export
  docs/proto/proto-docs.md
  proto/axelar/axelarnet/v1beta1/genesis.proto
  x/axelarnet/keeper/genesis.go
  x/axelarnet/keeper/genesis_test.go
  x/axelarnet/keeper/keeper.go
  x/axelarnet/types/genesis.go
  x/axelarnet/types/genesis.pb.go
Labels: enhancement, backport needed

#1793 feat(vald): arbitrum support
  vald/config/config_test.go
  vald/config/testdata/config.toml
  vald/evm/evm.go
  vald/evm/evm_test.go
  vald/evm/rpc/arbitrum.go
  vald/evm/rpc/client.go
  vald/evm/rpc/ethereum.go
  vald/evm/rpc/ethereum_2.go
  vald/evm/rpc/mock/client.go
  vald/evm/rpc/moonbeam.go
  vald/evm/rpc/types.go
  vald/start.go
  x/evm/types/config.go
Labels: enhancement

#1804 fix: update tendermint protos
  Makefile
  third_party/proto/proofs.proto
  third_party/proto/tendermint/abci/types.proto
  third_party/proto/tendermint/types/evidence.proto
  third_party/proto/tendermint/types/types.proto
Labels: next release

#1802 fix(evm): ensure mint commands do not have a zero ID
  x/evm/keeper/grpc_query_test.go
  x/evm/keeper/querier.go
  x/evm/types/command.go
  x/evm/types/command_test.go
  x/evm/types/testutils/types.go
  x/evm/types/types.go
  x/evm/types/types_test.go
  x/nexus/exported/testutils/rand.go
Labels: next release

#1800 chore: rosetta support
  Dockerfile.rosetta
  docs/cli/axelard_rosetta.md
  go.mod
  go.sum
  rosetta/entrypoint.sh
Labels: backport needed, next release

#1801 feat(multisig): allow validators to opt out of keygen
  docs/cli/axelard_tx_multisig.md
  docs/cli/axelard_tx_multisig_keygen.md
  docs/cli/axelard_tx_multisig_keygen_opt-in.md
  docs/cli/axelard_tx_multisig_keygen_opt-out.md
  docs/cli/axelard_tx_multisig_keygen_start.md
  docs/cli/toc.md
  docs/proto/proto-docs.md
  proto/axelar/multisig/v1beta1/events.proto
  proto/axelar/multisig/v1beta1/service.proto
  proto/axelar/multisig/v1beta1/tx.proto
  third_party/proto/proofs.proto
  utils/testutils/setup.go
  x/multisig/client/cli/tx.go
  x/multisig/keeper/keeper.go
  x/multisig/keeper/keygen.go
  x/multisig/keeper/keygen_test.go
  x/multisig/keeper/msg_server.go
  x/multisig/keeper/snapshotter.go
  x/multisig/keeper/snapshotter_test.go
  x/multisig/module.go
  x/multisig/types/codec.go
  x/multisig/types/events.pb.go
  x/multisig/types/expected_keepers.go
  x/multisig/types/mock/expected_keepers.go
  x/multisig/types/msg_keygen_optin.go
  x/multisig/types/msg_keygen_optout.go
  x/multisig/types/service.pb.go
  x/multisig/types/service.pb.gw.go
  x/multisig/types/tx.pb.go
Labels: next release

#1810 fix(vald): log errors after cleanup (#1796)
  utils/abci.go
  vald/start.go
  x/multisig/types/signing_test.go
Labels: backport

#1819 fix(reward)!: don't reward validators who have opted out of keygen
  app/app.go
  x/multisig/keeper/keygen.go
  x/multisig/keeper/keygen_test.go
  x/multisig/keeper/snapshotter.go
  x/multisig/keeper/snapshotter_test.go
  x/multisig/types/expected_keepers.go
  x/multisig/types/mock/expected_keepers.go
  x/reward/abci.go
  x/reward/types/expected_keepers.go
Labels: bug, next release

#1812 fix: backport cosmos sdk patch
  Makefile
  docs/cli/axelard_start.md
  go.mod
  go.sum
  scripts/sed.sh
  sdk-utils/broadcast/broadcast_test.go
  third_party/proto/cosmos/staking/v1beta1/tx.proto
  third_party/proto/proofs.proto
  third_party/proto/tendermint/abci/types.proto
  third_party/proto/tendermint/types/evidence.proto
  third_party/proto/tendermint/types/types.proto
  utils/proto.go
  utils/proto_test.go
  vald/state_test.go
  x/multisig/keeper/msg_server_test.go
  x/permission/keeper/genesis_test.go
  x/reward/keeper/msg_server_test.go
  x/vote/keeper/keeper.go
  x/vote/keeper/poll.go
Labels: backport

#1824 feat(vald): add arbitrum support to vald (#1793)
  go.mod
  go.sum
  vald/config/config_test.go
  vald/config/testdata/config.toml
  vald/evm/evm.go
  vald/evm/evm_test.go
  vald/evm/rpc/arbitrum.go
  vald/evm/rpc/client.go
  vald/evm/rpc/ethereum.go
  vald/evm/rpc/ethereum_2.go
  vald/evm/rpc/mock/client.go
  vald/evm/rpc/mock/rpcClient.go
  vald/evm/rpc/moonbeam.go
  vald/evm/rpc/rpcClient.go
  vald/evm/rpc/types.go
  vald/start.go
  x/evm/types/config.go
Labels: backport

#1817 chore: rosetta support
  Dockerfile.rosetta
  docs/cli/axelard_rosetta.md
  go.mod
  go.sum
  rosetta/entrypoint.sh
Labels: backport
