Repository axelarnetwork/axelar-core, pull requests merged in 2022-04, with the labels that each got.

#1407 feat(evm): support gateway tx callContract
  cmd/axelard/cmd/vald/evm/evm.go
  cmd/axelard/cmd/vald/evm/evm_test.go
  docs/proto/proto-docs.md
  proto/evm/v1beta1/types.proto
  x/evm/abci.go
  x/evm/abci_test.go
  x/evm/keeper/chainKeeper.go
  x/evm/keeper/msg_server.go
  x/evm/types/msg_vote_confirm_gateway_tx.go
  x/evm/types/types.go
  x/evm/types/types.pb.go
Labels: enhancement

#1408 feat(evm): genesis import&export for events and confirmedEventQueue
  docs/proto/proto-docs.md
  proto/evm/v1beta1/genesis.proto
  proto/utils/v1beta1/queuer.proto
  testutils/rand/rand.go
  utils/queuer.go
  utils/queuer.pb.go
  utils/queuer_test.go
  x/evm/keeper/chainKeeper.go
  x/evm/keeper/genesis.go
  x/evm/keeper/genesis_test.go
  x/evm/types/genesis.go
  x/evm/types/genesis.pb.go
  x/evm/types/msg_vote_confirm_gateway_tx.go
  x/evm/types/testutils/types.go
  x/evm/types/types.go
Labels: enhancement, next release

#1414 chore: update deps
  go.mod
  go.sum
Labels: next release

#1416 feat(evm): pass source tx information to approveContractCall commands
  contract-artifacts/version-config.json
  x/evm/types/types.go
  x/evm/types/types_test.go
Labels: next release

#1412 fix(evm): fixes some bug for general msg passing
  x/evm/abci.go
  x/evm/types/types.go
  x/evm/types/types_test.go
Labels: bug, next release

#1410 feat: enforce msg restriction rules
  Makefile
  docs/proto/proto-docs.md
  go.mod
  go.sum
  proto/axelarnet/v1beta1/tx.proto
  proto/evm/v1beta1/tx.proto
  proto/nexus/v1beta1/tx.proto
  proto/permission/exported/v1beta1/types.proto
  proto/permission/v1beta1/tx.proto
  proto/reward/v1beta1/tx.proto
  proto/snapshot/v1beta1/tx.proto
  proto/tss/v1beta1/tx.proto
  scripts/protocgen.sh
  third_party/proto/google/protobuf/descriptor.proto
  x/ante/restricted_tx.go
  x/ante/restricted_tx_test.go
  x/ante/types/expected_keepers.go
  x/ante/types/mock/alias.go
  x/ante/types/mock/alias_mock.go
  x/ante/types/mock/expected_keepers.go
  x/axelarnet/types/tx.pb.go
  x/evm/types/tx.pb.go
  x/nexus/types/tx.pb.go
  x/permission/exported/proto.go
  x/permission/exported/types.go
  x/permission/exported/types.pb.go
  x/permission/exported/types_test.go
  x/permission/keeper/keeper.go
  x/permission/keeper/migrate.go
  x/permission/module.go
  x/permission/types/tx.pb.go
  x/reward/types/tx.pb.go
  x/snapshot/types/tx.pb.go
  x/tss/types/tx.pb.go
Labels: next release

#1418 refactor(evm): set confirmed event on the source chain instead for gateway tx events
  x/evm/abci.go
  x/evm/abci_test.go
  x/evm/keeper/chainKeeper.go
  x/evm/keeper/msg_server.go
Labels: refactor, next release

#1417 fix: update the default min gas price
  cmd/axelard/cmd/root.go
Labels: next release

#1402 feat(vote): vote module and evm vote handler
  app/app.go
  cmd/axelard/cmd/vald/evm/evm.go
  cmd/axelard/cmd/vald/evm/evm_test.go
  docs/cli/axelard_tx_evm.md
  docs/cli/axelard_tx_evm_confirm-erc20-deposit.md
  docs/cli/toc.md
  docs/proto/proto-docs.md
  go.mod
  go.sum
  proto/evm/v1beta1/service.proto
  proto/evm/v1beta1/tx.proto
  proto/evm/v1beta1/types.proto
  proto/vote/exported/v1beta1/types.proto
  proto/vote/v1beta1/service.proto
  proto/vote/v1beta1/tx.proto
  x/evm/client/cli/tx.go
  x/evm/client/rest/tx.go
  x/evm/handler.go
  x/evm/keeper/chainKeeper.go
  x/evm/keeper/msg_server.go
  x/evm/keeper/msg_server_test.go
  x/evm/keeper/vote_handler.go
  x/evm/keeper/vote_handler_test.go
  x/evm/types/codec.go
  x/evm/types/expected_keepers.go
  x/evm/types/mock/expected_keepers.go
  x/evm/types/msg_deposit.go
  x/evm/types/service.pb.go
  x/evm/types/service.pb.gw.go
  x/evm/types/tx.pb.go
  x/evm/types/types.go
  x/evm/types/types.pb.go
  x/nexus/keeper/transfer.go
  x/vote/exported/types.go
  x/vote/exported/types.pb.go
  x/vote/handler.go
  x/vote/keeper/keeper.go
  x/vote/keeper/msg_server.go
  x/vote/module.go
  x/vote/types/codec.go
  x/vote/types/errors.go
  x/vote/types/events.go
  x/vote/types/expected_keepers.go
  x/vote/types/mock/expected_keepers.go
  x/vote/types/msg_vote.go
  x/vote/types/service.pb.go
  x/vote/types/service.pb.gw.go
  x/vote/types/tx.pb.go
  x/vote/types/vote_router.go
Labels: enhancement, refactor, next release

#1413 refactor(evm): move vote message to vote handler
  app/app.go
  cmd/axelard/cmd/vald/evm/evm.go
  cmd/axelard/cmd/vald/evm/evm_test.go
  docs/proto/proto-docs.md
  proto/evm/v1beta1/service.proto
  proto/evm/v1beta1/types.proto
  x/evm/handler.go
  x/evm/keeper/chainKeeper.go
  x/evm/keeper/msg_server.go
  x/evm/keeper/vote_handler.go
  x/evm/keeper/vote_handler_test.go
  x/evm/types/expected_keepers.go
  x/evm/types/mock/expected_keepers.go
  x/evm/types/service.pb.go
  x/evm/types/service.pb.gw.go
  x/evm/types/types.go
  x/evm/types/types.pb.go
Labels: next release

#1429 fix(build): fix build warning for mac os 12
  go.mod
  go.sum
Labels: patch-release

#1415 fix(vald): wait for rpc node to sync on vald lauch
  cmd/axelard/cmd/vald/config/config.go
  cmd/axelard/cmd/vald/start.go
  go.mod
  go.sum
Labels: patch-release

#1437 chore: backport tofnd key rotation support
  cmd/axelard/cmd/vald/config/config.go
  cmd/axelard/cmd/vald/start.go
  cmd/axelard/cmd/vald/tss/keygen.go
  cmd/axelard/cmd/vald/tss/sign.go
  cmd/axelard/cmd/vald/tss/tss.go
  docs/proto/proto-docs.md
  go.mod
  go.sum
  proto/tss/tofnd/v1beta1/common.proto
  proto/tss/tofnd/v1beta1/multisig.proto
  proto/tss/v1beta1/query.proto
  proto/tss/v1beta1/service.proto
  x/tss/keeper/grpc_query.go
  x/tss/keeper/grpc_query_test.go
  x/tss/module.go
  x/tss/tofnd/common.pb.go
  x/tss/tofnd/multisig.pb.go
  x/tss/types/query.pb.go
  x/tss/types/service.pb.go
  x/tss/types/service.pb.gw.go
Labels: patch-release

#1442 fix(build): fix build warning for mac os 12 (#1429)
  go.mod
  go.sum
Labels: patch-release

#1441 fix: emit events from cached end blocker (#1439)
  utils/abci.go
  utils/abci_test.go
Labels: backport

#1445 fix(evm): emit events from cached ctx
  x/evm/keeper/vote_handler.go
Labels: bug, backport needed

#1456 feat(ante): check minimum validator commission rate
  app/app.go
  x/ante/check_commission_rate.go
  x/ante/check_commission_rate_test.go
  x/ante/restricted_tx_test.go
Labels: enhancement, next release
