Repository axelarnetwork/axelar-core, pull requests merged in 2022-05, with the labels that each got.

#1461 fix(tss): fix validator key query
  cmd/axelard/cmd/vald/tss/tss.go
  x/tss/keeper/grpc_query.go
Labels: patch-release

#1474 feat(nexus): length bounded type ChainName
  x/nexus/exported/types.go
  x/nexus/exported/types_test.go
Labels: enhancement

#1466 feat(vote): grace period after completion
  app/app.go
  docs/proto/proto-docs.md
  go.mod
  go.sum
  proto/evm/v1beta1/params.proto
  proto/vote/exported/v1beta1/types.proto
  proto/vote/v1beta1/types.proto
  x/bitcoin/keeper/msg_server.go
  x/bitcoin/keeper/msg_server_test.go
  x/evm/keeper/migrate.go
  x/evm/keeper/migrate_test.go
  x/evm/keeper/msg_server.go
  x/evm/keeper/msg_server_test.go
  x/evm/keeper/vote_handler.go
  x/evm/keeper/vote_handler_test.go
  x/evm/types/expected_keepers.go
  x/evm/types/mock/expected_keepers.go
  x/evm/types/params.go
  x/evm/types/params.pb.go
  x/tss/keeper/msg_server.go
  x/vote/abci.go
  x/vote/abci_test.go
  x/vote/exported/mock/types.go
  x/vote/exported/types.go
  x/vote/exported/types.pb.go
  x/vote/keeper/genesis_test.go
  x/vote/keeper/keeper.go
  x/vote/keeper/migrate.go
  x/vote/keeper/migrate_test.go
  x/vote/keeper/msg_server.go
  x/vote/module.go
  x/vote/types/expected_keepers.go
  x/vote/types/mock/expected_keepers.go
  x/vote/types/mock/types.go
  x/vote/types/types.go
  x/vote/types/types.pb.go
  x/vote/types/types_test.go
Labels: enhancement, next release

#1446 fix(query): use axelar instead of cosmos chain for fee query
  x/nexus/keeper/grpc_query.go
  x/nexus/keeper/grpc_query_test.go
  x/nexus/module.go
  x/nexus/types/expected_keepers.go
  x/nexus/types/mock/expected_keepers.go
Labels: nice to have

#1481 feat(evm): release rewards for both voters who voted before and after completion within the grace period
  x/evm/keeper/vote_handler.go
Labels: next release

#1485 fix(evm): use default separator for command ID
  x/evm/types/types.go
  x/evm/types/types_test.go
Labels: next release

#1486 fix(nexus): delete uaxl fee info
  go.mod
  go.sum
  x/nexus/keeper/migrate.go
  x/nexus/keeper/migrate_test.go
  x/tss/keeper/migrate.go
Labels: next release

#1489 fix(tss): deprecated sig metadata was being emitted
  x/bitcoin/keeper/msg_server.go
  x/tss/abci.go
  x/tss/exported/types.go
  x/tss/keeper/migrate_test.go
Labels: bug

#1491 fix(vote): filter out voters who do not have any voting power
  go.mod
  go.sum
  x/evm/types/params.go
  x/reward/abci.go
  x/vote/exported/types.go
  x/vote/keeper/keeper.go
  x/vote/keeper/keeper_test.go
  x/vote/types/types.go
  x/vote/types/types_test.go
Labels: bug

#1492 fix(vote)!: filter out voters who do not have any voting power (#1491)
  go.mod
  go.sum
  x/evm/types/params.go
  x/reward/abci.go
  x/vote/exported/types.go
  x/vote/keeper/keeper.go
  x/vote/keeper/keeper_test.go
  x/vote/types/types.go
  x/vote/types/types_test.go
Labels: bug, backport

#1502 fix(evm): evm command decode for transferOwnership/Operatorship
  x/evm/abci.go
  x/evm/types/types.go
  x/evm/types/types_test.go
Labels: bug
