Repository axelarnetwork/axelar-core, pull requests merged in 2022-08, with the labels that each got.

#1662 fix(evm): add query event
  docs/cli/axelard_query_evm.md
  docs/cli/axelard_query_evm_event.md
  docs/cli/toc.md
  x/evm/client/cli/query.go
Labels: bug

#1654 refactor(tss): remove tss references
  docs/cli/axelard_vald-start.md
  vald/healthcheck.go
  vald/start.go
  vald/tss/keygen.go
  vald/tss/keygen_test.go
  vald/tss/rpc/mock/rpcClient.go
  vald/tss/rpc/rpcClient.go
  vald/tss/sign.go
  vald/tss/sign_test.go
  vald/tss/timeout.go
  vald/tss/timeout_test.go
  vald/tss/tss.go
  vald/tss/tss_test.go
  x/tss/client/cli/tx.go
Labels: next release

#1670 fix(vald): validate confirmation events
  sdk-utils/broadcast/broadcast_test.go
  vald/evm/evm.go
  vald/evm/evm_test.go
  x/evm/keeper/baseKeeper.go
Labels: next release

#1664 feat(multisig): add keygen session query
  docs/cli/axelard_query_multisig.md
  docs/cli/axelard_query_multisig_keygen-session.md
  docs/cli/toc.md
  docs/proto/proto-docs.md
  proto/axelar/multisig/v1beta1/query.proto
  proto/axelar/multisig/v1beta1/service.proto
  x/multisig/client/cli/query.go
  x/multisig/exported/mock/types.go
  x/multisig/exported/types.go
  x/multisig/keeper/grpc_query.go
  x/multisig/keeper/grpc_query_test.go
  x/multisig/keeper/keygen.go
  x/multisig/types/expected_keepers.go
  x/multisig/types/mock/expected_keepers.go
  x/multisig/types/query.pb.go
  x/multisig/types/service.pb.go
  x/multisig/types/service.pb.gw.go
  x/multisig/types/testutils/rand.go
Labels: next release

#1692 fix(reward)!: clear rewards if validator is no longer bonded on releasing rewards
  x/reward/keeper/reward_pool.go
  x/reward/keeper/reward_pool_test.go
Labels: bug

#1694 refactor(axelarnet): msg server uses keeper
  x/axelarnet/handler.go
  x/axelarnet/keeper/keeper.go
  x/axelarnet/keeper/keeper_test.go
  x/axelarnet/keeper/msg_server.go
  x/axelarnet/keeper/msg_server_test.go
  x/axelarnet/types/expected_keepers.go
  x/axelarnet/types/mock/expected_keepers.go
  x/nexus/exported/testutils/rand.go
Labels: refactor

#1696 fix(evm): check burner address in confirm deposit
  x/evm/keeper/chainKeeper.go
  x/evm/keeper/keeper_test.go
  x/evm/keeper/msg_server.go
  x/evm/keeper/msg_server_test.go
  x/evm/types/expected_keepers.go
  x/evm/types/mock/expected_keepers.go
Labels: enhancement, next release

#1704 refactor(vote): use cached passing weight
  x/vote/keeper/poll.go
Labels: next release

#1709 fix(nexus)!: fix recipient address validation
  x/evm/types/types.go
  x/nexus/keeper/transfer.go
Labels: next release

#1702 refactor(axelarnet): retry failed transfer
  app/app.go
  docs/proto/proto-docs.md
  proto/axelar/axelarnet/v1beta1/types.proto
  x/axelarnet/abci.go
  x/axelarnet/abci_test.go
  x/axelarnet/handler.go
  x/axelarnet/keeper/genesis_test.go
  x/axelarnet/keeper/ibc_transfer.go
  x/axelarnet/keeper/keeper.go
  x/axelarnet/keeper/keeper_test.go
  x/axelarnet/keeper/msg_server.go
  x/axelarnet/keeper/msg_server_test.go
  x/axelarnet/module.go
  x/axelarnet/types/expected_keepers.go
  x/axelarnet/types/mock/expected_keepers.go
  x/axelarnet/types/testutils/types.go
  x/axelarnet/types/types.go
  x/axelarnet/types/types.pb.go
Labels: next release

#1710 feat(axelarnet): v023 migration
  x/axelarnet/keeper/genesis_test.go
  x/axelarnet/keeper/keeper.go
  x/axelarnet/keeper/migrate.go
  x/axelarnet/keeper/migrate_test.go
  x/axelarnet/module.go
Labels: next release

#1714 fix(evm)!: check deposit status before creating transfer
  x/evm/abci.go
  x/evm/abci_test.go
Labels: bug, next release

#1708 fix!: axelar address check
  app/app.go
  x/axelarnet/keeper/address_validator.go
  x/axelarnet/keeper/address_validator_test.go
  x/axelarnet/types/expected_keepers.go
  x/axelarnet/types/mock/expected_keepers.go
  x/evm/keeper/address_validator_test.go
  x/nexus/keeper/genesis_test.go
  x/nexus/keeper/keeper_test.go
  x/nexus/keeper/transfer_test.go
Labels: next release

#1713 test(vote)!: add tests for VoteRequest, Params and VoteRouter
  testutils/fake/store.go
  x/vote/types/msg_vote.go
  x/vote/types/msg_vote_test.go
  x/vote/types/params.go
  x/vote/types/params_test.go
  x/vote/types/vote_router.go
  x/vote/types/vote_router_test.go
Labels: next release

#1716 refactor(nexus)!: optimize keeper access for chain state
  x/evm/keeper/vote_handler.go
  x/evm/types/expected_keepers.go
  x/evm/types/mock/expected_keepers.go
  x/nexus/exported/types.go
  x/nexus/keeper/chain.go
  x/nexus/keeper/genesis.go
  x/nexus/keeper/keeper_test.go
  x/nexus/keeper/migrate.go
  x/nexus/keeper/migrate_test.go
  x/nexus/types/types.go
  x/nexus/types/types_test.go
Labels: next release
