Repository axelarnetwork/axelar-core, pull requests merged in 2022-02, with the labels that each got.

#1269 fix: add event attributes
  x/evm/keeper/msg_server.go
  x/tss/abci.go
Labels: next release

#1243 feat(evm): add query for confirmation height
  docs/cli/axelard_query_evm.md
  docs/cli/axelard_query_evm_confirmation-height.md
  docs/cli/toc.md
  docs/proto/proto-docs.md
  proto/evm/v1beta1/query.proto
  proto/evm/v1beta1/service.proto
  x/evm/client/cli/query.go
  x/evm/keeper/grpc_query.go
  x/evm/types/query.pb.go
  x/evm/types/service.pb.go
  x/evm/types/service.pb.gw.go
Labels: enhancement

#1299 feat(tss): heartbeat should not affect multisig signing
  x/snapshot/exported/types.go
  x/snapshot/exported/types_test.go
  x/tss/keeper/keeperSign.go
  x/tss/keeper/keeperSign_test.go
  x/tss/keeper/msg_server.go
  x/tss/types/expected_keepers.go
  x/tss/types/mock/expected_keepers.go
Labels: enhancement

#1267 feat(migration): migrate states in axelarnet and nexus
  app/app.go
  x/axelarnet/keeper/migrate.go
  x/axelarnet/keeper/migrate_test.go
  x/axelarnet/legacy/key.go
  x/axelarnet/module.go
  x/evm/module.go
  x/nexus/keeper/migrate.go
  x/nexus/keeper/migrate_test.go
  x/nexus/legacy/exported/types.pb.go
  x/nexus/legacy/store.go
  x/nexus/legacy/types.pb.go
  x/nexus/module.go
  x/nexus/types/expected_keepers.go
  x/nexus/types/mock/expected_keepers.go
Labels: next release

#1308 fix(tss): sign event not including participant set
  x/tss/keeper/keeperSign.go
Labels: bug

#1315 fix(docker): axelard version was not being set
  Dockerfile
  Dockerfile.binaries
  Dockerfile.protocgen
Labels: bug

#1320 fix(evm): the SignCommands should set command batch status to be signing
  x/evm/keeper/msg_server.go
  x/evm/keeper/msg_server_test.go
Labels: bug

#1316 feat(ante)!: allow refundable txs with more than a single message
  x/ante/check_refund.go
  x/tss/keeper/msg_server.go
Labels: next release

#1317 fix(tss): remove keygen/sign metrics to avoid metrics bloat
  x/tss/abci.go
  x/tss/keeper/msg_server.go
Labels: bug, next release

#1329 fix: go mod tidy
  go.mod
Labels: next release

#1324 feat(evm): update bytecode for v2.1.0
  x/evm/keeper/keeper_test.go
  x/evm/keeper/querier.go
  x/evm/types/contracts.go
  x/evm/types/types.go
Labels: enhancement, next release

#1335 feat(evm): adjustments to CLI query commands
  docs/proto/proto-docs.md
  proto/evm/v1beta1/query.proto
  x/evm/client/cli/query.go
  x/evm/keeper/querier.go
  x/evm/types/cli_errors.go
  x/evm/types/query.pb.go
Labels: enhancement
