Repository axelarnetwork/axelar-core, pull requests merged in 2022-07, with the labels that each got.

#1577 feat(multisig): keygen grace period and key creation
  docs/proto/proto-docs.md
  go.sum
  proto/axelar/multisig/v1beta1/events.proto
  proto/axelar/multisig/v1beta1/params.proto
  proto/axelar/multisig/v1beta1/types.proto
  x/multisig/abci.go
  x/multisig/abci_test.go
  x/multisig/keeper/keeper.go
  x/multisig/keeper/msg_server.go
  x/multisig/keeper/msg_server_test.go
  x/multisig/module.go
  x/multisig/types/events.go
  x/multisig/types/events.pb.go
  x/multisig/types/expected_keepers.go
  x/multisig/types/genesis_test.go
  x/multisig/types/mock/expected_keepers.go
  x/multisig/types/params.go
  x/multisig/types/params.pb.go
  x/multisig/types/types.go
  x/multisig/types/types.pb.go
  x/multisig/types/types_test.go
Labels: enhancement

#1582 feat(multisig): add module into app
  app/app.go
  docs/cli/axelard_tx.md
  docs/cli/axelard_tx_multisig.md
  docs/cli/axelard_tx_multisig_start-keygen.md
  docs/cli/toc.md
  x/multisig/client/cli/tx.go
  x/multisig/keeper/keeper.go
  x/multisig/keeper/msg_server_test.go
  x/multisig/module.go
Labels: enhancement

#1579 feat(vald): handle multisig keygen
  cmd/axelard/cmd/vald/multisig/grpc_client.go
  cmd/axelard/cmd/vald/multisig/keygen.go
  cmd/axelard/cmd/vald/multisig/keygen_test.go
  cmd/axelard/cmd/vald/multisig/mgr.go
  cmd/axelard/cmd/vald/multisig/mock/rpcClient.go
  cmd/axelard/cmd/vald/start.go
  cmd/axelard/cmd/vald/tofnd_grpc/client.go
  x/multisig/types/codec.go
  x/multisig/types/msg_submit_pub_key.go
Labels: enhancement

#1584 feat(multisig): types for signing
  docs/proto/proto-docs.md
  go.mod
  go.sum
  proto/axelar/multisig/exported/v1beta1/types.proto
  proto/axelar/multisig/v1beta1/types.proto
  x/multisig/exported/types.pb.go
  x/multisig/types/keygen.go
  x/multisig/types/signing.go
  x/multisig/types/signing_test.go
  x/multisig/types/testutils/rand.go
  x/multisig/types/types.go
  x/multisig/types/types.pb.go
Labels: enhancement

#1586 feat(multisig): methods needed to perform multisig signing
  x/multisig/types/keygen.go
  x/multisig/types/signing.go
  x/multisig/types/signing_test.go
Labels: enhancement

#1588 feat(multisig): handle signing session completion/expiry in the end blocker
  docs/proto/proto-docs.md
  proto/axelar/multisig/v1beta1/events.proto
  x/multisig/abci.go
  x/multisig/abci_test.go
  x/multisig/keeper/keeper.go
  x/multisig/types/events.go
  x/multisig/types/events.pb.go
  x/multisig/types/expected_keepers.go
  x/multisig/types/mock/expected_keepers.go
Labels: enhancement

#1589 feat(vald): handle multisig signing
  cmd/axelard/cmd/vald/multisig/keygen.go
  cmd/axelard/cmd/vald/multisig/mgr.go
  cmd/axelard/cmd/vald/multisig/signing.go
  cmd/axelard/cmd/vald/multisig/signing_test.go
  cmd/axelard/cmd/vald/start.go
  go.mod
  go.sum
Labels: enhancement

#1598 fix: disallow unbonded chain maintainer registration
  x/nexus/keeper/msg_server.go
  x/snapshot/keeper/keeper.go
  x/snapshot/keeper/keeper_test.go
Labels: next release

#1597 feat(multisig): key rotation
  docs/proto/proto-docs.md
  proto/axelar/multisig/v1beta1/events.proto
  proto/axelar/multisig/v1beta1/types.proto
  utils/store.go
  x/multisig/keeper/keeper.go
  x/multisig/keeper/msg_server_test.go
  x/multisig/keeper/rotation.go
  x/multisig/keeper/rotation_test.go
  x/multisig/keeper/signing.go
  x/multisig/types/events.go
  x/multisig/types/events.pb.go
  x/multisig/types/types.go
  x/multisig/types/types.pb.go
Labels: enhancement

#1615 fix(multisig): sign sender address for pubkey authentication
  cmd/axelard/cmd/vald/multisig/keygen.go
  x/multisig/types/msg_submit_pub_key.go
Labels: bug, next release

#1612 feat(evm): handle weighted key transfer with the new multisig module
  app/app.go
  x/evm/handler.go
  x/evm/keeper/chainKeeper.go
  x/evm/keeper/keeper_test.go
  x/evm/keeper/msg_server.go
  x/evm/keeper/msg_server_test.go
  x/evm/module.go
  x/evm/types/events.go
  x/evm/types/expected_keepers.go
  x/evm/types/mock/expected_keepers.go
  x/evm/types/types.go
  x/evm/types/types_test.go
  x/multisig/exported/mock/types.go
  x/multisig/exported/types.go
  x/multisig/keeper/rotation.go
  x/multisig/keeper/rotation_test.go
  x/multisig/types/keygen.go
Labels: enhancement

#1525 fix(nexus): recipient address query should return chain name, not chain.
  x/nexus/keeper/grpc_query.go
Labels: bug

#1620 feat(evm): unblock command creation even during key transfer
  go.mod
  go.sum
  x/evm/abci.go
  x/evm/keeper/msg_server.go
  x/evm/keeper/msg_server_test.go
Labels: next release

#1622 feat(multisig): auto-deactivate old key
  docs/proto/proto-docs.md
  proto/axelar/multisig/v1beta1/params.proto
  x/multisig/exported/mock/types.go
  x/multisig/exported/types.go
  x/multisig/keeper/rotation.go
  x/multisig/keeper/rotation_test.go
  x/multisig/types/keygen.go
  x/multisig/types/params.go
  x/multisig/types/params.pb.go
Labels: enhancement

#1596 feat: tss migration and tss reward pool migration
  app/app.go
  cmd/axelard/cmd/genreward.go
  docs/cli/axelard_set-genesis-reward.md
  docs/proto/proto-docs.md
  proto/axelar/evm/v1beta1/query.proto
  proto/axelar/reward/v1beta1/params.proto
  x/ante/ante.go
  x/ante/check_proxy.go
  x/ante/check_refund.go
  x/ante/restricted_tx_test.go
  x/ante/types/expected_keepers.go
  x/evm/keeper/grpc_query.go
  x/evm/types/query.pb.go
  x/multisig/keeper/keygen.go
  x/multisig/keeper/rotation.go
  x/multisig/keeper/rotation_test.go
  x/reward/abci.go
  x/reward/keeper/migrate.go
  x/reward/keeper/migrate_test.go
  x/reward/module.go
  x/reward/types/expected_keepers.go
  x/reward/types/params.go
  x/reward/types/params.pb.go
  x/tss/keeper/keeper.go
  x/tss/keeper/migrate.go
  x/tss/keeper/migrate_test.go
  x/tss/module.go
  x/tss/types/expected_keepers.go
  x/tss/types/mock/expected_keepers.go
Labels: next release

#1619 feat(multisig): rotate key tx
  app/app.go
  docs/cli/axelard_tx_multisig.md
  docs/cli/axelard_tx_multisig_rotate.md
  docs/cli/toc.md
  docs/proto/proto-docs.md
  proto/axelar/multisig/v1beta1/service.proto
  proto/axelar/multisig/v1beta1/tx.proto
  x/multisig/client/cli/tx.go
  x/multisig/keeper/msg_server.go
  x/multisig/keeper/msg_server_test.go
  x/multisig/module.go
  x/multisig/types/codec.go
  x/multisig/types/expected_keepers.go
  x/multisig/types/mock/expected_keepers.go
  x/multisig/types/msg_rotate_key.go
  x/multisig/types/service.pb.go
  x/multisig/types/service.pb.gw.go
  x/multisig/types/tx.pb.go
Labels: next release

#1625 feat(evm): add command batch ID in sig metadata
  x/evm/keeper/msg_server.go
  x/evm/types/types.go
Labels: next release

#1573 feat(evm): increase gas consumption for init poll
  x/vote/keeper/keeper.go
  x/vote/keeper/keeper_test.go
Labels: next release

#1608 feat(nexus): use quadratic weights for chain activation
  app/app.go
  x/evm/keeper/msg_server.go
  x/nexus/handler.go
  x/nexus/keeper/msg_server.go
  x/nexus/module.go
  x/nexus/types/expected_keepers.go
  x/nexus/types/mock/expected_keepers.go
  x/snapshot/exported/mock/types.go
  x/snapshot/exported/types.go
  x/snapshot/keeper/keeper.go
Labels: next release

#1595 fix(ante): account for max change rate for min commission check
  app/app.go
  go.mod
  go.sum
  x/ante/check_commission_rate.go
  x/ante/check_commission_rate_test.go
  x/ante/types/expected_keepers.go
  x/ante/types/mock/expected_keepers.go
Labels: next release

#1630 chore(evm): bump contract version
  contract-version.json
  x/evm/keeper/keeper_test.go
  x/evm/types/contracts.go
Labels: next release

#1633 feat: set order migrations
  app/app.go
Labels: next release

#1635 fix(evm): return empty burner code hash for external tokens
  x/evm/keeper/chainKeeper.go
  x/evm/keeper/grpc_query.go
  x/evm/types/types.go
Labels: next release

#1634 fix(reward): remove use of illegibility
  app/app.go
  x/reward/abci.go
  x/reward/module.go
  x/reward/types/expected_keepers.go
  x/reward/types/mock/expected_keepers.go
Labels: next release

#1643 fix(evm): transform signature
  x/evm/keeper/grpc_query.go
  x/multisig/exported/types.go
  x/multisig/types/types.go
Labels: bug

#1642 fix(multisig): convert utils.AppendStr and utils.KeyFromStr to utils.LowerCaseKey
  x/multisig/keeper/keygen.go
  x/multisig/keeper/rotation.go
  x/tss/keeper/migrate.go
Labels: bug

#1613 chore: update cosmos sdk to v0.45.6
  docs/cli/axelard_query_feegrant.md
  docs/cli/axelard_query_feegrant_grants-by-grantee.md
  docs/cli/axelard_query_feegrant_grants-by-granter.md
  docs/cli/axelard_tx_staking_edit-validator.md
  docs/cli/toc.md
  go.mod
  go.sum
Labels: patch-release

#1647 fix(vald): bind tofnd flags to viper config
  cmd/axelard/cmd/vald/start.go
  docs/cli/axelard_vald-start.md
Labels: bug

#1628 feat(evm): command batch signature migration
  go.mod
  go.sum
  x/evm/keeper/migrate.go
  x/evm/keeper/migrate_test.go
  x/evm/module.go
  x/evm/types/expected_keepers.go
  x/evm/types/mock/expected_keepers.go
Labels: next release

#1538 refactor(axelarnet)!: move ibc transfer to endblocker
  docs/proto/proto-docs.md
  go.mod
  go.sum
  proto/axelar/axelarnet/v1beta1/genesis.proto
  proto/axelar/axelarnet/v1beta1/types.proto
  x/axelarnet/abci.go
  x/axelarnet/abci_test.go
  x/axelarnet/handler.go
  x/axelarnet/keeper/genesis.go
  x/axelarnet/keeper/genesis_test.go
  x/axelarnet/keeper/keeper.go
  x/axelarnet/keeper/keeper_test.go
  x/axelarnet/keeper/msg_server.go
  x/axelarnet/keeper/msg_server_test.go
  x/axelarnet/module.go
  x/axelarnet/types/expected_keepers.go
  x/axelarnet/types/genesis.go
  x/axelarnet/types/genesis.pb.go
  x/axelarnet/types/mock/expected_keepers.go
  x/axelarnet/types/types.go
  x/axelarnet/types/types.pb.go
Labels: refactor, next release

#1583 feat(abci): limit number of items to process in EndBlocker
  docs/proto/proto-docs.md
  proto/axelar/evm/v1beta1/params.proto
  proto/axelar/vote/v1beta1/params.proto
  x/evm/abci.go
  x/evm/abci_test.go
  x/evm/keeper/migrate.go
  x/evm/keeper/migrate_test.go
  x/evm/keeper/msg_server_test.go
  x/evm/types/params.go
  x/evm/types/params.pb.go
  x/evm/types/testutils/types.go
  x/vote/abci.go
  x/vote/abci_test.go
  x/vote/keeper/migrate.go
  x/vote/keeper/migrate_test.go
  x/vote/types/expected_keepers.go
  x/vote/types/mock/expected_keepers.go
  x/vote/types/params.go
  x/vote/types/params.pb.go
Labels: enhancement, next release

#1648 fix!: fix token address check, reward clearing, and batch query
  cmd/axelard/cmd/vald/evm/evm.go
  testutils/rand/rand.go
  x/evm/keeper/grpc_query.go
  x/multisig/abci.go
  x/multisig/abci_test.go
  x/multisig/types/signing.go
  x/multisig/types/testutils/rand.go
  x/multisig/types/types.go
Labels: bug, next release
