Repository axelarnetwork/axelar-core, pull requests merged in 2022-06, with the labels that each got.

#1527 fix(vote)!: methods Poll.SetExpired and Poll.AllowOverride should have pointer receiver
  go.mod
  go.sum
  x/vote/types/types.go
  x/vote/types/types_test.go
Labels: bug

#1553 feat(snapshot): implement the keeper method CreateSnapshot
  go.mod
  go.sum
  utils/testutils/threshold.go
  x/snapshot/exported/mock/types.go
  x/snapshot/exported/types.go
  x/snapshot/exported/types_test.go
  x/snapshot/keeper/genesis_test.go
  x/snapshot/keeper/keeper.go
  x/snapshot/keeper/keeper_test.go
  x/snapshot/keeper/mock/alias.go
  x/snapshot/keeper/mock/mock.go
Labels: enhancement

#1555 fix(vald): fix concurrent access to keys cache
  cmd/axelard/cmd/vald/tss/keygen.go
  cmd/axelard/cmd/vald/tss/sign.go
  cmd/axelard/cmd/vald/tss/tss.go
  go.sum
Labels: patch-release
