Repository axelarnetwork/axelar-core, pull requests merged in 2022-01, with the labels that each got.

#1158 feat(nexus): add msg to activate chain
  docs/cli/axelard_tx_nexus.md
  docs/cli/axelard_tx_nexus_activate-chain.md
  docs/cli/toc.md
  docs/proto/proto-docs.md
  proto/nexus/v1beta1/service.proto
  proto/nexus/v1beta1/tx.proto
  x/ante/restricted_tx.go
  x/nexus/abci.go
  x/nexus/client/cli/tx.go
  x/nexus/handler.go
  x/nexus/keeper/msg_server.go
  x/nexus/module.go
  x/nexus/types/codec.go
  x/nexus/types/msg_activate_chain.go
  x/nexus/types/service.pb.go
  x/nexus/types/service.pb.gw.go
  x/nexus/types/tx.pb.go
Labels: refactor

#1180 fix: panic in msg processing
  cmd/axelard/cmd/vald/tss/keygen.go
  cmd/axelard/cmd/vald/tss/sign.go
  proto/tss/v1beta1/tx.proto
  x/tss/keeper/msg_server.go
  x/tss/types/msg_sign.go
  x/tss/types/tx.pb.go
  x/tss/types/types_test.go
Labels: bug

#1181 fix(nexus): skip registering maintainers for cosmos chains
  app/app.go
  x/axelarnet/keeper/keeper.go
  x/nexus/handler.go
  x/nexus/keeper/msg_server.go
  x/nexus/module.go
  x/nexus/types/expected_keepers.go
Labels: bug

#1183 fix(tss): add validation of fields that cannot be empty slices
  x/tss/types/msg_ack.go
  x/tss/types/msg_submit_multisig_pubkey.go
  x/tss/types/msg_submit_multisig_signatures.go
Labels: bug

#1185 fix(tss): validator check in heartbeat
  x/tss/keeper/msg_server.go
Labels: bug

#1187 fix(keeper): append the delimiter to the iterator key
  utils/store.go
  x/tss/keeper/keeperSign.go
Labels: bug

#1186 fix(axelarnet): escrow all funds upon confirmation
  docs/cli/axelard_tx_axelarnet.md
  docs/cli/axelard_tx_axelarnet_confirm-deposit.md
  docs/cli/toc.md
  docs/proto/proto-docs.md
  proto/axelarnet/v1beta1/tx.proto
  x/axelarnet/client/cli/tx.go
  x/axelarnet/client/rest/tx.go
  x/axelarnet/keeper/msg_server.go
  x/axelarnet/keeper/msg_server_test.go
  x/axelarnet/types/expected_keepers.go
  x/axelarnet/types/mock/expected_keepers.go
  x/axelarnet/types/msg_confirm_deposit.go
  x/axelarnet/types/tx.pb.go
Labels: bug

#1198 fix(tss): shorter signed blocks window
  cmd/axelard/cmd/gentss.go
  docs/cli/axelard_set-genesis-tss.md
  docs/proto/proto-docs.md
  proto/tss/v1beta1/params.proto
  x/snapshot/exported/mock/types.go
  x/snapshot/exported/types.go
  x/snapshot/keeper/keeper.go
  x/snapshot/keeper/keeper_test.go
  x/tss/keeper/keeper.go
  x/tss/types/params.go
  x/tss/types/params.pb.go
Labels: bug

#1193 feat: in-place storage upgrade from v0.11 to v0.13
  app/app.go
  docs/proto/proto-docs.md
  proto/nexus/v1beta1/types.proto
  x/axelarnet/keeper/msg_server.go
  x/axelarnet/keeper/msg_server_test.go
  x/axelarnet/types/expected_keepers.go
  x/axelarnet/types/mock/expected_keepers.go
  x/nexus/keeper/chain.go
  x/nexus/keeper/genesis_test.go
  x/nexus/keeper/keeper_test.go
  x/nexus/keeper/migrate.go
  x/nexus/keeper/migrate_test.go
  x/nexus/keeper/transfer.go
  x/nexus/module.go
  x/nexus/types/expected_keepers.go
  x/nexus/types/mock/expected_keepers.go
  x/nexus/types/types.go
  x/nexus/types/types.pb.go
Labels: enhancement

#1211 feat: vald should start from latest block if the one in state is too old
  cmd/axelard/cmd/vald/start.go
Labels: enhancement

#1221 feat(nexus): query to retrieve transfers
  docs/cli/axelard_query_nexus.md
  docs/cli/axelard_query_nexus_transfers-for-chain.md
  docs/cli/toc.md
  docs/proto/proto-docs.md
  go.mod
  proto/nexus/v1beta1/query.proto
  proto/nexus/v1beta1/service.proto
  x/nexus/client/cli/query.go
  x/nexus/exported/types.go
  x/nexus/exported/types_test.go
  x/nexus/keeper/grpc_query.go
  x/nexus/keeper/grpc_query_test.go
  x/nexus/keeper/transfer.go
  x/nexus/types/query.pb.go
  x/nexus/types/service.pb.go
  x/nexus/types/service.pb.gw.go
Labels: enhancement

#1225 feat(vald): moonbeam finality
  cmd/axelard/cmd/vald/evm/evm.go
  cmd/axelard/cmd/vald/evm/evm_test.go
  cmd/axelard/cmd/vald/evm/main/main.go
  cmd/axelard/cmd/vald/evm/rpc/mock/rpcClient.go
  cmd/axelard/cmd/vald/evm/rpc/rpcClient.go
  cmd/axelard/cmd/vald/evm/rpc/types.go
  go.mod
Labels: enhancement, backport

#1224 feat(vald): moonbeam finality
  cmd/axelard/cmd/vald/evm/evm.go
  cmd/axelard/cmd/vald/evm/evm_test.go
  cmd/axelard/cmd/vald/evm/main/main.go
  cmd/axelard/cmd/vald/evm/rpc/mock/rpcClient.go
  cmd/axelard/cmd/vald/evm/rpc/rpcClient.go
  cmd/axelard/cmd/vald/evm/rpc/types.go
  go.mod
Labels: enhancement

#1233 fix: include transfer ID in deposit logs (#1220)
  x/axelarnet/keeper/msg_server.go
  x/evm/keeper/msg_server.go
  x/evm/types/types.go
  x/tss/abci.go
  x/tss/keeper/keeper.go
Labels: backport

#1232 feat(nexus): query to retrieve transfers (#1221)
  docs/cli/axelard_query_nexus.md
  docs/cli/axelard_query_nexus_transfers-for-chain.md
  docs/cli/toc.md
  docs/proto/proto-docs.md
  proto/nexus/v1beta1/query.proto
  proto/nexus/v1beta1/service.proto
  x/nexus/client/cli/query.go
  x/nexus/exported/types.go
  x/nexus/exported/types_test.go
  x/nexus/keeper/grpc_query.go
  x/nexus/keeper/grpc_query_test.go
  x/nexus/keeper/transfer.go
  x/nexus/types/query.pb.go
  x/nexus/types/service.pb.go
  x/nexus/types/service.pb.gw.go
Labels: backport

#1245 feat(vald): new EVM config field
  cmd/axelard/cmd/vald/evm/rpc/rpcClient.go
  cmd/axelard/cmd/vald/start.go
  x/evm/types/config.go
Labels: enhancement

#1241 feat(evm): burner info query
  docs/cli/axelard_query_evm.md
  docs/cli/axelard_query_evm_burner-info.md
  docs/cli/toc.md
  docs/proto/proto-docs.md
  proto/evm/v1beta1/query.proto
  proto/evm/v1beta1/service.proto
  x/evm/client/cli/query.go
  x/evm/keeper/baseKeeper.go
  x/evm/keeper/chainKeeper.go
  x/evm/keeper/genesis.go
  x/evm/keeper/genesis_test.go
  x/evm/keeper/grpc_query.go
  x/evm/keeper/keeper_test.go
  x/evm/keeper/msg_server.go
  x/evm/keeper/msg_server_test.go
  x/evm/module.go
  x/evm/types/expected_keepers.go
  x/evm/types/mock/expected_keepers.go
  x/evm/types/query.pb.go
  x/evm/types/service.pb.go
  x/evm/types/service.pb.gw.go
Labels: enhancement

#1234 feat!: external erc20 support
  app/app.go
  docs/cli/axelard_tx_evm_create-deploy-token.md
  docs/proto/proto-docs.md
  proto/evm/v1beta1/params.proto
  proto/evm/v1beta1/tx.proto
  proto/evm/v1beta1/types.proto
  x/evm/client/cli/tx.go
  x/evm/client/rest/tx.go
  x/evm/keeper/chainKeeper.go
  x/evm/keeper/keeper_test.go
  x/evm/keeper/migrate.go
  x/evm/keeper/migrate_test.go
  x/evm/keeper/msg_server.go
  x/evm/keeper/msg_server_test.go
  x/evm/keeper/querier.go
  x/evm/keeper/querier_test.go
  x/evm/legacy/params.go
  x/evm/module.go
  x/evm/types/contracts.go
  x/evm/types/expected_keepers.go
  x/evm/types/mock/expected_keepers.go
  x/evm/types/msg_create_deploy_token.go
  x/evm/types/params.go
  x/evm/types/params.pb.go
  x/evm/types/tests/types_test.go
  x/evm/types/testutils/types.go
  x/evm/types/tx.pb.go
  x/evm/types/types.go
  x/evm/types/types.pb.go
Labels: enhancement

#1258 feat(evm)!: sign key role for command batch
  x/evm/keeper/chainKeeper.go
  x/evm/keeper/keeper_test.go
  x/evm/keeper/migrate.go
  x/evm/keeper/msg_server.go
  x/evm/types/contracts.go
  x/evm/types/expected_keepers.go
  x/evm/types/mock/expected_keepers.go
  x/evm/types/params.go
  x/evm/types/types.go
  x/evm/types/types_test.go
Labels: enhancement

#1259 fix(tss): add key ID validation upon heartbeat
  x/tss/keeper/msg_server.go
Labels: bug

#1264 fix: evm chain param validation
  x/evm/types/params.go
Labels: bug

#1263 fix: skip logging during ante simulation
  x/ante/ante.go
Labels: bug

#1268 feat(evm)!: prioritize executing burn commands
  utils/queuer.go
  utils/queuer_test.go
  x/evm/keeper/chainKeeper.go
  x/evm/keeper/keeper_test.go
  x/evm/types/genesis.go
  x/evm/types/types.go
Labels: enhancement, next release

#1265 feat(evm)!: versioning burner
  docs/proto/proto-docs.md
  proto/evm/v1beta1/params.proto
  proto/evm/v1beta1/types.proto
  x/evm/keeper/chainKeeper.go
  x/evm/keeper/keeper_test.go
  x/evm/keeper/migrate.go
  x/evm/keeper/migrate_test.go
  x/evm/keeper/msg_server.go
  x/evm/keeper/msg_server_test.go
  x/evm/legacy/contracts.go
  x/evm/legacy/params.go
  x/evm/types/contracts.go
  x/evm/types/expected_keepers.go
  x/evm/types/mock/expected_keepers.go
  x/evm/types/params.go
  x/evm/types/params.pb.go
  x/evm/types/testutils/types.go
  x/evm/types/types.go
  x/evm/types/types.pb.go
Labels: enhancement, next release
