Repository axelarnetwork/axelar-core, pull requests merged in 2022-11, with the labels that each got.

#1826 fix!: add delimiter to paginated kv store iterator by prefix
  x/evm/keeper/chainKeeper.go
  x/nexus/keeper/keeper_test.go
  x/nexus/keeper/transfer.go
  x/nexus/keeper/transfer_test.go
Labels: bug, next release

#1822 refactor(evm): make event handling atomic
  x/evm/abci.go
  x/evm/abci_test.go
Labels: refactor, next release

#1820 feat(nexus)!: set rate limit during asset registration
  utils/int.go
  utils/int_test.go
  x/axelarnet/keeper/msg_server.go
  x/axelarnet/keeper/msg_server_test.go
  x/axelarnet/types/expected_keepers.go
  x/axelarnet/types/mock/expected_keepers.go
  x/evm/keeper/msg_server.go
  x/evm/keeper/msg_server_test.go
  x/evm/types/expected_keepers.go
  x/evm/types/mock/expected_keepers.go
  x/evm/types/types.go
  x/nexus/keeper/chain.go
  x/nexus/keeper/genesis_test.go
  x/nexus/keeper/grpc_query_test.go
  x/nexus/keeper/keeper_test.go
  x/nexus/keeper/rate_limit_test.go
  x/nexus/keeper/transfer_test.go
Labels: next release

#1821 feat(evm)!: rate limit contract call with token
  x/evm/abci.go
  x/evm/abci_test.go
  x/evm/keeper/msg_server.go
  x/evm/types/expected_keepers.go
  x/evm/types/mock/expected_keepers.go
Labels: enhancement, next release

#1836 fix(axelarnet): wrong port/channel being used for rate limiting incoming IBC transfer
  x/axelarnet/rate_limit.go
  x/axelarnet/rate_limit_test.go
  x/axelarnet/types/testutils/types.go
Labels: bug
