Repository axelarnetwork/axelar-core, pull requests merged in 2022-03, with the labels that each got.

#1343 fix(evm): token query response
  x/evm/keeper/querier.go
Labels: bug

#1331 fix: add more attributes, logs, and checks
  docs/proto/proto-docs.md
  proto/nexus/v1beta1/service.proto
  x/axelarnet/handler.go
  x/axelarnet/keeper/msg_server.go
  x/axelarnet/keeper/msg_server_test.go
  x/axelarnet/types/events.go
  x/axelarnet/types/msg_add_chain.go
  x/bitcoin/handler.go
  x/bitcoin/keeper/msg_server.go
  x/evm/handler.go
  x/evm/keeper/msg_server.go
  x/evm/types/events.go
  x/evm/types/types.go
  x/nexus/types/service.pb.go
  x/nexus/types/service.pb.gw.go
Labels: next release

#1380 chore: add all modules in SetOrder
  app/app.go
Labels: next release

#1395 feat(evm): make ContractCallWithToken for destination chain instead of the source chain
  cmd/axelard/cmd/vald/evm/evm_test.go
  docs/proto/proto-docs.md
  proto/evm/v1beta1/types.proto
  x/evm/keeper/chainKeeper.go
  x/evm/keeper/msg_server.go
  x/evm/keeper/msg_server_test.go
  x/evm/types/expected_keepers.go
  x/evm/types/mock/expected_keepers.go
  x/evm/types/msg_vote_confirm_gateway_tx.go
  x/evm/types/types.go
  x/evm/types/types.pb.go
Labels: enhancement

#1399 fix(evm): query pending-commands when having command approveContractCallWithMint
  x/evm/keeper/grpc_query.go
  x/evm/keeper/grpc_query_test.go
  x/evm/keeper/querier.go
  x/evm/types/types.go
  x/evm/types/types_test.go
Labels: bug

#1404 feat(evm): support gateway tx sendToken
  cmd/axelard/cmd/vald/evm/evm.go
  cmd/axelard/cmd/vald/evm/evm_test.go
  docs/proto/proto-docs.md
  proto/evm/v1beta1/types.proto
  x/evm/abci.go
  x/evm/abci_test.go
  x/evm/keeper/chainKeeper.go
  x/evm/keeper/msg_server.go
  x/evm/types/expected_keepers.go
  x/evm/types/mock/expected_keepers.go
  x/evm/types/msg_vote_confirm_gateway_tx.go
  x/evm/types/types.go
  x/evm/types/types.pb.go
  x/nexus/keeper/transfer.go
Labels: enhancement

#1401 refactor(evm): move CreateApproveContractCalls into EndBlocker and support SendToken
  cmd/axelard/cmd/vald/evm/evm.go
  cmd/axelard/cmd/vald/evm/evm_test.go
  docs/cli/axelard_tx_evm.md
  docs/cli/axelard_tx_evm_create-approve-contract-calls.md
  docs/cli/toc.md
  docs/proto/proto-docs.md
  proto/evm/v1beta1/service.proto
  proto/evm/v1beta1/tx.proto
  proto/evm/v1beta1/types.proto
  testutils/fake/interfaces/mock/store.go
  testutils/fake/interfaces/store.go
  utils/abci.go
  utils/abci_test.go
  utils/mock/abci.go
  x/evm/abci.go
  x/evm/abci_test.go
  x/evm/client/cli/tx.go
  x/evm/handler.go
  x/evm/keeper/chainKeeper.go
  x/evm/keeper/msg_server.go
  x/evm/keeper/msg_server_test.go
  x/evm/module.go
  x/evm/types/codec.go
  x/evm/types/expected_keepers.go
  x/evm/types/mock/expected_keepers.go
  x/evm/types/msg_create_approve_contract_calls.go
  x/evm/types/msg_vote_confirm_gateway_tx.go
  x/evm/types/service.pb.go
  x/evm/types/service.pb.gw.go
  x/evm/types/tx.pb.go
  x/evm/types/types.go
  x/evm/types/types.pb.go
  x/nexus/keeper/transfer.go
Labels: enhancement, refactor
