Repository axelarnetwork/axelar-core, pull requests merged in 2023-06, with the labels that each got.

#1947 feat(reward): add inflation rate query (#1941)
  docs/proto/proto-docs.md
  proto/axelar/reward/v1beta1/query.proto
  proto/axelar/reward/v1beta1/service.proto
  testutils/rand/rand.go
  utils/int.go
  x/reward/client/cli/query.go
  x/reward/keeper/grpc_query.go
  x/reward/keeper/grpc_query_test.go
  x/reward/module.go
  x/reward/types/query.pb.go
  x/reward/types/service.pb.go
  x/reward/types/service.pb.gw.go
Labels: backport

#1949 fix(vald): allow processing old key transfer tx
  vald/evm/evm.go
  vald/evm/evm_test.go
  vald/start.go
Labels: patch-release

#1952 feat(axelarnet)!: min deposit requirement based on the contract addresses in the call contracts proposal
  app/app.go
  docs/proto/proto-docs.md
  proto/axelar/axelarnet/v1beta1/params.proto
  x/axelarnet/keeper/genesis.go
  x/axelarnet/keeper/hooks.go
  x/axelarnet/keeper/hooks_test.go
  x/axelarnet/keeper/keeper.go
  x/axelarnet/keeper/migrate.go
  x/axelarnet/keeper/migrate_test.go
  x/axelarnet/module.go
  x/axelarnet/types/codec.go
  x/axelarnet/types/expected_keepers.go
  x/axelarnet/types/mock/expected_keepers.go
  x/axelarnet/types/params.go
  x/axelarnet/types/params.pb.go
  x/axelarnet/types/types.go
  x/nexus/keeper/keeper_test.go
Labels: enhancement

#1939 feat(vald): batch call rpc clients to get transaction receipts
  vald/evm/evm.go
  vald/evm/evm_test.go
  vald/evm/rpc/client.go
  vald/evm/rpc/ethereum.go
  vald/evm/rpc/mock/client.go
  vald/evm/rpc/mock/ethereum.go
  vald/start.go
Labels: enhancement, next release

#1959 chore(evm)!: lower batch confirmation limit
  x/evm/types/msg_confirm_gateway_txs.go
Labels: next release

#1965 chore: allow skipping initial rate limit when deploying tokens
  docs/cli/axelard_tx_evm_create-deploy-token.md
  docs/cli/toc.md
  go.mod
  go.sum
  x/evm/client/cli/tx.go
  x/evm/keeper/msg_server.go
  x/evm/keeper/msg_server_test.go
  x/evm/types/msg_create_deploy_token.go
Labels: next release
