Repository axelarnetwork/axelar-core, pull requests merged in 2023-05, with the labels that each got.

#1931 feat(vald): add FinalityOverride option
  .github/workflows/check-go-generate.yaml
  Makefile
  vald/config/config_test.go
  vald/config/decoding.go
  vald/config/testdata/config.toml
  vald/evm/rpc/client.go
  vald/evm/rpc/finalityoverride_string.go
  vald/evm/rpc/types.go
  vald/start.go
  x/evm/types/config.go
Labels: enhancement, backport needed

#1936 feat(vald): add FinalityOverride option (#1931)
  .github/workflows/check-go-generate.yaml
  Makefile
  vald/config/config_test.go
  vald/config/decoding.go
  vald/config/testdata/config.toml
  vald/evm/rpc/client.go
  vald/evm/rpc/finalityoverride_string.go
  vald/evm/rpc/types.go
  vald/start.go
  x/evm/types/config.go
Labels: backport

#1929 feat(evm)!: confirm gateway txs
  client/docs/static/openapi/index.html
  client/docs/static/openapi/openapi.yaml
  client/docs/static/swagger/swagger.yaml
  docs/cli/axelard_tx_evm.md
  docs/cli/axelard_tx_evm_confirm-gateway-tx.md
  docs/cli/axelard_tx_evm_confirm-gateway-txs.md
  docs/cli/toc.md
  docs/proto/proto-docs.md
  proto/axelar/evm/v1beta1/events.proto
  proto/axelar/evm/v1beta1/service.proto
  proto/axelar/evm/v1beta1/tx.proto
  x/evm/client/cli/tx.go
  x/evm/handler.go
  x/evm/keeper/msg_server.go
  x/evm/keeper/msg_server_test.go
  x/evm/types/codec.go
  x/evm/types/events.pb.go
  x/evm/types/msg_confirm_gateway_txs.go
  x/evm/types/service.pb.go
  x/evm/types/service.pb.gw.go
  x/evm/types/tx.pb.go
Labels: enhancement

#1944 fix: use previous cosign version (#1922)
  .github/workflows/build-docker-image-and-binaries.yaml
Labels: backport

#1945 feat: backport improvements to events
  docs/proto/proto-docs.md
  go.mod
  go.sum
  proto/axelar/axelarnet/v1beta1/events.proto
  proto/axelar/evm/v1beta1/events.proto
  proto/axelar/multisig/v1beta1/events.proto
  proto/axelar/nexus/v1beta1/events.proto
  x/axelarnet/types/events.pb.go
  x/evm/types/events.pb.go
  x/multisig/types/events.pb.go
  x/nexus/keeper/general_message.go
  x/nexus/types/events.pb.go
Labels: backport

#1946 feat(vald): latest finalized block cache (#1934)
  vald/evm/evm.go
  vald/evm/evm_test.go
  vald/evm/latest_finalized_block_cache.go
  vald/evm/latest_finalized_block_cache_test.go
  vald/evm/mock/latest_finalized_block_cache.go
  vald/evm/rpc/client.go
  vald/evm/rpc/ethereum.go
  vald/evm/rpc/ethereum_2.go
  vald/evm/rpc/mock/client.go
  vald/evm/rpc/moonbeam.go
  vald/start.go
Labels: backport

#1948 feat(vald): use finalized tag to check moonbeam finality (#1940)
  vald/evm/evm.go
  vald/evm/rpc/client.go
  vald/evm/rpc/moonbeam.go
  vald/evm/rpc/types.go
Labels: backport
