Repository axelarnetwork/axelar-core, pull requests merged in 2024-02, with the labels that each got.

#2085 fix(evm)!: only rate limit evm destination in evm module
  x/evm/abci.go
  x/evm/abci_test.go
Labels: next release

#2090 fix(app)!: run evm end blocker after nexus to process routed messages
  app/app.go
Labels: next release

#2087 ci(Makefile)!: enable wasm build by default in makefile
  .github/workflows/build-docker-image-and-binaries.yaml
  .github/workflows/build-latest-docker-image.yaml
  Dockerfile
  Dockerfile.debug
  Makefile
Labels: next release

#2091 chore: update cometbft/ibc deps
  go.mod
  go.sum
Labels: next release

#2105 fix!: override wasm default param after initialization
  app/app.go
  app/wasm.go
  app/wasm_test.go
Labels: bug

#2111 feat(cli): add `--wasm-dir` flag to start command
  app/app.go
  app/app_test.go
  app/keepers.go
  cmd/axelard/cmd/root.go
  docs/cli/axelard_start.md
Labels: backport needed, next release

#2114 fix(app): register wasm snapshot extension for state-sync
  app/app.go
Labels: backport needed, next release

#2115 fix(wasm): migrate wasm cache dir to the new path
  app/app.go
  go.mod
  go.sum
Labels: backport needed, next release
